name: Build pdf's
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make latexmk texlive-lang-european texlive-latex-extra
      - name: Build pdf
        run: |
          make -C latex
          mkdir artifact
          cp latex/*.pdf artifact/.
      - name: Archive
        uses: actions/upload-artifact@v7
        with:
          name: PDF 
          path: artifact
