name: Build pdf's
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get install -y make latexmk texlive-lang-european
      - name: Build pdf
        run: |
          make
          mkdir artifact
          cp *.pdf artifact/.
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: PDF 
          path: artifact
